---

- name: Get debian mysql user
  register: _mysql_debian_username
  shell: grep user /etc/mysql/debian.cnf | tail -n 1 | cut -d'=' -f2 | awk '{print $1}'
  changed_when: false
  ignore_errors: true
  when: automysqlbackup_username is not defined

- name: Get debian mysql password
  register: _mysql_debian_password
  shell: grep password /etc/mysql/debian.cnf | tail -n 1 | cut -d'=' -f2 | awk '{print $1}'
  changed_when: false
  ignore_errors: true
  when: automysqlbackup_password is not defined

- name: Setup config
  template:
    src: 'automysqlbackup.conf'
    dest: '/etc/automysqlbackup/automysqlbackup.conf'
    owner: root
    group: root
    mode: '400'

#- name: Add automysqlbackup cron job
#  cron:
#    name: "automysqlbackup"
#    minute: "{{ automysqlbackup_cron_minute }}"
#    hour: "{{ automysqlbackup_cron_hour }}"
#    day: "{{ automysqlbackup_cron_day }}"
#    month: "{{ automysqlbackup_cron_month }}"
#    weekday: "{{ automysqlbackup_cron_weekday }}"
#    user: root
#    job: >
#      $(NOW=$(date +"%Y-%m-%d_%Hh%Mm");
#      /usr/local/bin/automysqlbackup {{ automysqlbackup_log_dir }}/backup-$NOW.log
#      && echo $NOW > {{ automysqlbackup_backup_dir }}/automysqlbackup_status)

- name: Export priviledges
  cron:
    name: "mysql priviledges"
    minute: "{{ automysqlbackup_cron_minute }}"
    hour: "{{ automysqlbackup_cron_hour }}"
    day: "{{ automysqlbackup_cron_day }}"
    month: "{{ automysqlbackup_cron_month }}"
    weekday: "{{ automysqlbackup_cron_weekday }}"
    user: root
    job: "/usr/bin/mysqldump -nt mysql user db | gzip > /var/backup/db/privileges.sql.gz"
  when: automysqlbackup_export_priviledges

#- name: Export priviledges
#  cron:
#    name: "env test"
#    minute: "{{ automysqlbackup_cron_minute }}"
#    hour: "{{ automysqlbackup_cron_hour }}"
#    day: "{{ automysqlbackup_cron_day }}"
#    month: "{{ automysqlbackup_cron_month }}"
#    weekday: "{{ automysqlbackup_cron_weekday }}"
#    user: root
#    job: "env > /tmp/env.output"
#  when: automysqlbackup_export_priviledges

- name: Export wrapper
  cron:
    name: "wrapper"
    minute: "*/3"
    hour: "{{ automysqlbackup_cron_hour }}"
    day: "{{ automysqlbackup_cron_day }}"
    month: "{{ automysqlbackup_cron_month }}"
    weekday: "{{ automysqlbackup_cron_weekday }}"
    user: root
    job: /usr/local/bin/automysqlbackup-wrapper.sh
