---
- name: Install automysqlbackup
  copy:
    src: 'automysqlbackup.sh'
    dest: '/usr/local/bin/automysqlbackup'
    owner: root
    group: root
    mode: '0555'

- name: Install automysqlbackup-wrapper
  template:
    src: 'automysqlbackup-wrapper.sh'
    dest: '/usr/local/bin/automysqlbackup-wrapper.sh'
    owner: root
    group: root
    mode: '0555'

- name: Ensure directories exist
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0740'
  with_items:
    - '/etc/automysqlbackup'
    - '{{ automysqlbackup_backup_dir }}'
    - '{{ automysqlbackup_log_dir }}'
